name: Update Google Scholar Publications

on:
  schedule:
    - cron: "0 0 * * 0"  # every week
  workflow_dispatch:

jobs:
  update-scholar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch Scholar publications
        uses: akashrchandran/scholar-profile-readme@master
        with:
          scholar_id: 2iwarAMAAAAJ
          max_publications: 10
          sort_by: "year"
      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update publications from Google Scholar" || echo "No changes"
          git push
